### ISSUE TITLE
Memory leak in Runtime or Environment

### ISSUE THREAD

**Issue by axic** [wasm3/wasm3#203]
In our project we have [updated](https://github.com/wasmx/fizzy/pull/739) from 0.4.7 to 11f813d7ed659ed7c5b3faf6df0ff6e8f715f4e5 and seeing memory leaks now. 

See the [CI log here](https://app.circleci.com/pipelines/github/wasmx/fizzy/6285/workflows/28be9728-da05-470e-a7d1-1b74dd509571/jobs/53531):
```
Direct leak of 85 byte(s) in 5 object(s) allocated from:
    #0 0x510f42 in calloc (/home/builder/build/bin/fizzy-unittests+0x510f42)
    #1 0xd41e9d in m3_Malloc /home/builder/build/_deps/src/wasm3/source/m3_core.c:109:18
    #2 0xb76259 in fizzy::test::create_wasm3_engine() /home/builder/project/test/utils/wasm3_engine.cpp:53:12
    #3 0xb1a193 in wasm_engine_multi_mixed_args_ret_i32_Test::TestBody() /home/builder/project/test/unittests/wasm_engine_test.cpp:221:23
    #4 0xd8ea13 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest.cc:2433:10
    #5 0xd768ba in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest.cc:2469:14
    #6 0xd5a9e8 in testing::Test::Run() /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest.cc:2508:5
    #7 0xd5b539 in testing::TestInfo::Run() /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest.cc:2684:11
    #8 0xd5bbab in testing::TestSuite::Run() /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest.cc:2816:28
    #9 0xd66be7 in testing::internal::UnitTestImpl::RunAllTests() /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest.cc:5338:44
    #10 0xd93393 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest.cc:2433:10
    #11 0xd78e6a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest.cc:2469:14
    #12 0xd6678d in testing::UnitTest::Run() /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest.cc:4925:10
    #13 0xb7c3c0 in RUN_ALL_TESTS() /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/include/gtest/gtest.h:2473:46
    #14 0xb7c3a5 in main /home/builder/.hunter/_Base/0dd1ee8/30c40e8/4a56575/Build/GTest/Source/googletest/src/gtest_main.cc:45:10
    #15 0x7fe1c90b1cc9 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26cc9)
```

I am not entirely clear what is leaving it, but reading through the changes/API I think our code must be using it correctly, and we had no leaks with 0.4.7.

**Comment by vshymanskyy** [comment]
Thanks for investigating this!
