### ISSUE TITLE
pc points to the zero page in RunCode

### ISSUE THREAD

**Issue by ret2ddme** [wasm3/wasm3#378]
**feel free to close it**
`commit 9dcfce271c2fac86823725fc9ec0f75309d820e4`

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
───────────────────────────────────────────────────────────────────────────────────────────────[ REGISTERS ]────────────────────────────────────────────────────────────────────────────────────────────────
 RAX  0x0
 RBX  0x626000000100 ◂— 0x626000000100
 RCX  0x0
 RDX  0x631000014800 —▸ 0x626000000100 ◂— 0x626000000100
 RDI  0x62d0000004a8 ◂— 0x0
 RSI  0x631000000800 ◂— 0x1000000000000
 R8   0x60ea20 (op_Select_i32_ssr) ◂— lea    rsp, [rsp - 0x98]
 R9   0x631000000808 ◂— 0xfff075ff00000004
 R10  0x3
 R11  0x10004e6dd21c ◂— 0x0
 R12  0x7ffe73726d80 ◂— 0x41b58ab3
 R13  0x7ffe737290e2 ◂— 0x3d4c4c4548530032 /* '2' */
 R14  0x0
 R15  0x60300000001a ◂— 0x0
 RBP  0x62d000000418 —▸ 0x5f4520 (op_Entry) ◂— lea    rsp, [rsp - 0x98]
 RSP  0x7ffe73726ce8 —▸ 0x647436 (m3_CallArgv+4374) ◂— test   rax, rax
 RIP  0x0
─────────────────────────────────────────────────────────────────────────────────────────────────[ DISASM ]─────────────────────────────────────────────────────────────────────────────────────────────────
Invalid address 0x0










─────────────────────────────────────────────────────────────────────────────────────────────────[ STACK ]──────────────────────────────────────────────────────────────────────────────────────────────────
00:0000│ rsp 0x7ffe73726ce8 —▸ 0x647436 (m3_CallArgv+4374) ◂— test   rax, rax
01:0008│     0x7ffe73726cf0 ◂— 0x0
02:0010│     0x7ffe73726cf8 —▸ 0xfffce6e4db4 ◂— 0x0
03:0018│     0x7ffe73726d00 ◂— 0x0
04:0020│     0x7ffe73726d08 —▸ 0x63fb58 (m3_FindFunction+3320) ◂— mov    rdi, qword ptr [rsp]
05:0028│     0x7ffe73726d10 —▸ 0x7ffe73726da0 —▸ 0x6110000000b0 —▸ 0x60f000000040 —▸ 0x626000000100 ◂— ...
06:0030│     0x7ffe73726d18 —▸ 0x611000000100 —▸ 0x62d000000418 —▸ 0x5f4520 (op_Entry) ◂— lea    rsp, [rsp - 0x98]
07:0038│     0x7ffe73726d20 —▸ 0x626000002a98 —▸ 0x631000000800 ◂— 0x1000000000000
───────────────────────────────────────────────────────────────────────────────────────────────[ BACKTRACE ]────────────────────────────────────────────────────────────────────────────────────────────────
 ► f 0              0x0
   f 1         0x647436 m3_CallArgv+4374
   f 2         0x647436 m3_CallArgv+4374
   f 3         0x4d1230 repl_call+3088
   f 4         0x4e05de main+5854
   f 5   0x7f459e925083 __libc_start_main+243
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
pwndbg> bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000647436 in RunCode (_pc=0x62d000000418, _sp=0x631000000800, _mem=0x631000014800, _r0=0, _fp0=1.6532053103774119e-316) at /data/wasm3/source/./m3_exec_defs.h:58
#2  m3_CallArgv (i_function=0x6110000000b0, i_argc=<optimized out>, i_argc@entry=0, i_argv=i_argv@entry=0x0) at /data/wasm3/source/m3_env.c:953
#3  0x00000000004d1230 in repl_call (name=<optimized out>, argc=<optimized out>, argv=<optimized out>) at /data/wasm3/platforms/app/main.c:274
#4  0x00000000004e05de in main (i_argc=0, i_argv=<optimized out>) at /data/wasm3/platforms/app/main.c:634
#5  0x00007f459e925083 in __libc_start_main (main=0x4def00 <main>, argc=2, argv=0x7ffe73727ae8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe73727ad8) at ../csu/libc-start.c:308
#6  0x000000000041ea2e in _start ()
```
Asan
```
==3530894==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x62d000000418 sp 0x7ffd1c533fc8 T0)
==3530894==Hint: pc points to the zero page.
==3530894==The signal is caused by a READ memory access.
==3530894==Hint: address points to the zero page.
    #0 0x0  (<unknown module>)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
==3530894==ABORTING
```

[RunCode.zip](https://github.com/wasm3/wasm3/files/9440878/RunCode.zip)

**Comment by vshymanskyy** [comment]
@ret2ddme  sorry I will be closing any fuzzer reports, as this is covered by #344
